filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /data/jenkins/kenh14-notify-prod/logs/notify.log
output.kafka:
  codec.format:
    string: '%{[@timestamp]} %{[message]}'
  hosts: ['172.26.33.29:9092','172.26.33.31:9092','172.26.33.32:9092','172.26.33.33:9092']
  topic: kenh14-logging-p
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
